/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dongnaoedu_dnffmpegplayer_JasonPlayer */

#ifndef _Included_com_dongnaoedu_dnffmpegplayer_JasonPlayer
#define _Included_com_dongnaoedu_dnffmpegplayer_JasonPlayer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_dongnaoedu_dnffmpegplayer_JasonPlayer_render
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
